CREATE TABLE sracollector.GEO_DATA_SET
(
    ID         SERIAL PRIMARY KEY,
    NCBI_ID    INTEGER     NOT NULL,
    REQUEST_ID VARCHAR     NOT NULL REFERENCES sracollector.REQUEST (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    GDS        VARCHAR(50) NOT NULL,
    UNIQUE (REQUEST_ID, GDS)
);

CREATE TABLE sracollector.GEO_PLATFORM
(
    ID         SERIAL PRIMARY KEY,
    NCBI_ID    INTEGER     NOT NULL,
    REQUEST_ID VARCHAR     NOT NULL REFERENCES sracollector.REQUEST (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    GPL        VARCHAR(50) NOT NULL,
    UNIQUE (REQUEST_ID, GPL)
);

CREATE TABLE sracollector_dev.GEO_DATA_SET
(
    ID         SERIAL PRIMARY KEY,
    NCBI_ID    INTEGER     NOT NULL,
    REQUEST_ID VARCHAR     NOT NULL REFERENCES sracollector_dev.REQUEST (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    GDS        VARCHAR(50) NOT NULL,
    UNIQUE (REQUEST_ID, GDS)
);

CREATE TABLE sracollector_dev.GEO_PLATFORM
(
    ID         SERIAL PRIMARY KEY,
    NCBI_ID    INTEGER     NOT NULL,
    REQUEST_ID VARCHAR     NOT NULL REFERENCES sracollector_dev.REQUEST (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    GPL        VARCHAR(50) NOT NULL,
    UNIQUE (REQUEST_ID, GPL)
);
