CREATE TABLE SRACOLLECTOR.GEO_STUDY_SRA_PROJECT_LINK
(
    GEO_STUDY_ID   INTEGER NOT NULL,
    SRA_PROJECT_ID INTEGER NOT NULL,
    PRIMARY KEY (GEO_STUDY_ID, SRA_PROJECT_ID),
    FOREIGN KEY (GEO_STUDY_ID) REFERENCES SRACOLLECTOR.GEO_STUDY (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (SRA_PROJECT_ID) REFERENCES SRACOLLECTOR.SRA_PROJECT (ID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE SRACOLLECTOR_DEV.GEO_STUDY_SRA_PROJECT_LINK
(
    GEO_STUDY_ID   INTEGER NOT NULL,
    SRA_PROJECT_ID INTEGER NOT NULL,
    PRIMARY KEY (GEO_STUDY_ID, SRA_PROJECT_ID),
    FOREIGN KEY (GEO_STUDY_ID) REFERENCES SRACOLLECTOR_DEV.GEO_STUDY (ID),
    FOREIGN KEY (SRA_PROJECT_ID) REFERENCES SRACOLLECTOR_DEV.SRA_PROJECT (ID)
);

ALTER TABLE SRACOLLECTOR.SRA_PROJECT DROP CONSTRAINT SRA_PROJECT_GEO_STUDY_ID_FKEY;
ALTER TABLE SRACOLLECTOR.SRA_PROJECT DROP CONSTRAINT SRA_PROJECT_GEO_STUDY_ID_SRP_KEY;
ALTER TABLE SRACOLLECTOR.SRA_PROJECT DROP COLUMN GEO_STUDY_ID;


ALTER TABLE SRACOLLECTOR_DEV.SRA_PROJECT DROP CONSTRAINT SRA_PROJECT_GEO_STUDY_ID_FKEY;
ALTER TABLE SRACOLLECTOR_DEV.SRA_PROJECT DROP CONSTRAINT SRA_PROJECT_GEO_STUDY_ID_SRP_KEY;
ALTER TABLE SRACOLLECTOR_DEV.SRA_PROJECT DROP COLUMN GEO_STUDY_ID;
