CREATE TABLE REQUEST (
    ID VARCHAR UNIQUE,
    QUERY VARCHAR(500) NOT NULL,
    GEO_COUNT INTEGER NOT NULL,
    CREATED_ON TIMESTAMP [] NOT NULL DEFAULT ARRAY[now()],
    GEO_COUNT INTEGER NOT NULL,
    PRIMARY KEY (ID)
)
