CREATE TABLE GEO_STUDY
(
    ID SERIAL PRIMARY KEY,
    NCBI_ID INTEGER NOT NULL,
    REQUEST_ID VARCHAR NOT NULL REFERENCES REQUEST (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    GSE VARCHAR(50) NOT NULL,
    UNIQUE (REQUEST_ID, GSE)
);
