CREATE TABLE GEO_STUDY
(
    ID SERIAL PRIMARY KEY,
    NCBI_ID INTEGER,
    REQUEST_ID VARCHAR REFERENCES REQUEST (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    GSE VARCHAR(50) NOT NULL,
    UNIQUE (NCBI_ID, REQUEST_ID, GSE)
);
