CREATE TABLE GEO_STUDY
(
    ID SERIAL PRIMARY KEY,
    STUDY_ID INTEGER,
    REQUEST_ID VARCHAR REFERENCES REQUEST (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    ACCESSION VARCHAR(50) NOT NULL,
    UNIQUE (STUDY_ID, REQUEST_ID, ACCESSION)
);
