CREATE TABLE SRA_PROJECT
(
    ID SERIAL PRIMARY KEY,
    SRP VARCHAR(50) NOT NULL,
    GEO_STUDY_ID INTEGER NOT NULL REFERENCES GEO_STUDY (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (GEO_STUDY_ID, SRP)
);
