CREATE TABLE SRA_RUN
(
    ID             SERIAL PRIMARY KEY,
    SRR            VARCHAR(50) NOT NULL CHECK (SRR LIKE 'SRR%'),
    SRA_PROJECT_ID INTEGER     NOT NULL REFERENCES SRA_PROJECT (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CREATED_ON     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (SRA_PROJECT_ID, SRR)
);
