CREATE TABLE SRA_RUN
(
    ID SERIAL PRIMARY KEY,
    SRR VARCHAR(50) NOT NULL,
    SRA_PROJECT_ID INTEGER NOT NULL REFERENCES SRA_PROJECT (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (SRA_PROJECT_ID, SRR)
);
