CREATE TABLE SRA_RUN
(
    ID SERIAL PRIMARY KEY,
    SRR VARCHAR(50) NOT NULL,
    REQUEST_ID VARCHAR REFERENCES REQUEST (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    SRA_PROJECT_ID INTEGER REFERENCES SRA_PROJECT (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    GEO_STUDY_ID INTEGER REFERENCES GEO_STUDY (
        ID
    ) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (GEO_STUDY_ID, SRA_PROJECT_ID, REQUEST_ID, SRR)
);
