CREATE TABLE SRA_RUN_METADATA
(
    ID         SERIAL PRIMARY KEY,
    SRA_RUN_ID INTEGER UNIQUE NOT NULL REFERENCES SRA_RUN (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SPOTS      BIGINT         NOT NULL,
    BASES      BIGINT         NOT NULL,
    ORGANISM   VARCHAR(500)   NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (SRA_RUN_ID, SPOTS, BASES, ORGANISM)
);

CREATE TABLE SRA_RUN_METADATA_PHRED
(
    ID                  SERIAL PRIMARY KEY,
    SRA_RUN_METADATA_ID INTEGER NOT NULL REFERENCES SRA_RUN_METADATA (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SCORE               INT     NOT NULL,
    READ_COUNT          BIGINT  NOT NULL,
    CREATED_ON          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SRA_RUN_METADATA_STATISTIC_READ
(
    ID                  SERIAL PRIMARY KEY,
    SRA_RUN_METADATA_ID INTEGER UNIQUE NOT NULL REFERENCES SRA_RUN_METADATA (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    NSPOTS              BIGINT         NOT NULL,
    LAYOUT              VARCHAR(50) CHECK (LAYOUT IN ('PAIRED', 'SINGLE')),
    READ_0_COUNT        BIGINT         NOT NULL,
    READ_0_AVERAGE      FLOAT          NOT NULL,
    READ_0_STDEV        FLOAT          NOT NULL,
    READ_1_COUNT        BIGINT         NOT NULL,
    READ_1_AVERAGE      FLOAT          NOT NULL,
    READ_1_STDEV        FLOAT          NOT NULL,
    CREATED_ON          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (SRA_RUN_METADATA_ID, NSPOTS, LAYOUT, READ_0_COUNT, READ_0_AVERAGE, READ_0_STDEV, READ_1_COUNT, READ_1_AVERAGE, READ_1_STDEV)
);
