CREATE TABLE SRA_PROJECT_MISSING
(
    ID                         SERIAL PRIMARY KEY,
    GEO_STUDY_ID               INTEGER      NOT NULL REFERENCES GEO_STUDY (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PYSRADB_ERROR_REFERENCE_ID INTEGER      NOT NULL REFERENCES PYSRADB_ERROR_REFERENCE (ID),
    DETAILS                    VARCHAR(500) NOT NULL
);
