CREATE TABLE SRA_RUN_MISSING
(
    ID                         SERIAL PRIMARY KEY,
    SRA_PROJECT_ID             INTEGER      NOT NULL REFERENCES SRA_PROJECT (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PYSRADB_ERROR_REFERENCE_ID INTEGER      NOT NULL REFERENCES PYSRADB_ERROR_REFERENCE (ID),
    DETAILS                    VARCHAR(500) NOT NULL
);
