CREATE TABLE SRA_RUN_METADATA
(
    ID         SERIAL PRIMARY KEY,
    SRA_RUN_ID INTEGER NOT NULL REFERENCES SRA_RUN (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SPOTS      BIGINT NOT NULL,
    BASES      BIGINT NOT NULL,
    ORGANISM   VARCHAR(500) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SRA_RUN_METADATA_PHRED
(
    ID                  SERIAL PRIMARY KEY,
    SRA_RUN_METADATA_ID INTEGER NOT NULL REFERENCES SRA_RUN_METADATA (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SCORE               INT     NOT NULL,
    READ_COUNT          BIGINT     NOT NULL,
    CREATED_ON          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SRA_RUN_METADATA_STATISTIC_READ
(
    ID                  SERIAL PRIMARY KEY,
    SRA_RUN_METADATA_ID INTEGER NOT NULL REFERENCES SRA_RUN_METADATA (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    NSPOTS              BIGINT NOT NULL,
    LAYOUT VARCHAR(50) CHECK (LAYOUT IN ('PAIRED','SINGLE')),
    CREATED_ON          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SRA_RUN_METADATA_READ
(
    ID                                 SERIAL PRIMARY KEY,
    SRA_RUN_METADATA_STATISTIC_READ_ID INTEGER NOT NULL REFERENCES SRA_RUN_METADATA_STATISTIC_READ (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    INDEX                              INT     NOT NULL,
    COUNT                              BIGINT     NOT NULL,
    AVERAGE                            FLOAT   NOT NULL,
    STDEV                              FLOAT   NOT NULL,
    CREATED_ON                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
