ALTER TABLE GEO_STUDY
    ADD CONSTRAINT CHECK_GSE_REGEX
        CHECK (GSE ~ '^GSE[0-9]+$');

ALTER TABLE GEO_EXPERIMENT
    ADD CONSTRAINT CHECK_GSM_REGEX
        CHECK (GSM ~ '^GSM[0-9]+$');

ALTER TABLE GEO_DATA_SET
    ADD CONSTRAINT CHECK_GDS_REGEX
        CHECK (GDS ~ '^GDS[0-9]+$');

ALTER TABLE GEO_PLATFORM
    ADD CONSTRAINT CHECK_GPL_REGEX
        CHECK (GPL ~ '^GPL[0-9]+$');

ALTER TABLE SRA_PROJECT
    ADD CONSTRAINT CHECK_SRP_REGEX
        CHECK (SRP ~ '^SRP[0-9]+$');

ALTER TABLE SRA_RUN
    ADD CONSTRAINT CHECK_SRR_REGEX
        CHECK (SRR ~ '^SRR[0-9]+$');
