[environments.default]
url = "jdbc:postgresql://sracollector.cgaqaljpdpat.eu-central-1.rds.amazonaws.com:5432/"
schemas=["sracollector", "sracollector_dev"]
user = "sracollector"
validateMigrationNaming = true
