DROP TABLE sracollector.geo_data_set CASCADE;
DROP TABLE sracollector.geo_experiment CASCADE;
DROP TABLE sracollector.geo_platform CASCADE;
DROP TABLE sracollector.geo_study CASCADE;
DROP TABLE sracollector.geo_study_sra_project_link CASCADE;
DROP TABLE sracollector.pysradb_error_reference CASCADE;
DROP TABLE sracollector.request CASCADE;
DROP TABLE sracollector.sra_project CASCADE;
DROP TABLE sracollector.sra_project_missing CASCADE;
DROP TABLE sracollector.sra_run CASCADE;
DROP TABLE sracollector.sra_run_missing CASCADE;
DELETE FROM flyway_schema_history;
