name: db
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  db-schema:
    if: false # Deactivated as the project is discontinued. More info in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Flyway Migration
        run: make db-migrations-prod
  db-diagram:
    if: false # Deactivated as the project is discontinued. More info in README
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Generate diagram
        run: make update-diagram
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          message: 🔄 Update database diagram
