name: deploy-and-test
on:
  - push
  - pull_request
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
  unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/unit-tests
    steps:
      - uses: actions/checkout@v4
      - run: poetry run pytest
  tf:
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: terraform apply -auto-approve
  integrations-tests:
    needs: tf
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/integration-tests
    steps:
      - run: poetry run pytest
