name: test-and-deploy
on:
  - push
  - pull_request
jobs:
  python3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/lambda/user_query/python3
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run coverage run -m pytest
  tf:
    needs: python3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: terraform apply -auto-approve
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "3452487-aebc1b5e-f2b1-4180-899f-e9e6781f911a" --integration-id "153979-${{ github.run_id }}"
          postman api lint 23f2737d-7c36-4a1c-96ec-a671d0f99cfc --integration-id 153979
