name: test-and-deploy
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  - push
  - pull_request
jobs:
  purge-queues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run python ./utils/purge-queues.py
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest tests/user-query/unit_test.py
  tf:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: terraform apply -auto-approve
  integrations-tests:
    needs: tf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest tests/user-query/integration_test.py
